---
version: 2
project_name: kubectl-netdrill
dist: ./dist/

force_token: github
env_files:
  gitea_token: ~/nope
  github_token: ~/nope

release:
  disable: false
  skip_upload: false
  github:
    owner: xenos76
    name: kubectl-netdrill

before:
  hooks:
    - go mod download
    - go mod tidy
    - mkdir -p completions manpages
    - sh -c "go run main.go completion bash > completions/kubectl-netdrill.bash"
    - sh -c "go run main.go completion zsh > completions/_kubectl-netdrill"
    - sh -c "go run main.go completion fish > completions/kubectl-netdrill.fish"
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . man --dest-dir manpages'
    - sh -c 'go run . man run --dest-dir manpages'
    - sh -c 'go run . man pod --dest-dir manpages'
    - sh -c 'go run . man deployment --dest-dir manpages'
    - sh -c 'go run . man debug --dest-dir manpages'
    - sh -c 'gzip manpages/*'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/xenos76/kubectl-netdrill/internal/cmd.Version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- .Arch }}
    wrap_in_directory: false
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

nfpms:
  - maintainer: Zeno Belli <xeno@os76.xyz>
    vendor: xenos76 on Github
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill, a network troubleshooting plugin for Kubernetes.
    license: MIT
    formats:
      - deb
      - rpm
      - apk

    release: "1"

    contents:
      - src: completions/kubectl-netdrill.bash
        dst: /etc/bash_completion.d/kubectl-netdrill

      - src: completions/kubectl-netdrill.fish
        dst: /usr/share/fish/vendor_completions.d/kubectl-netdrill.fish

      - src: completions/_kubectl-netdrill
        dst: /usr/share/zsh/vendor-completions/_kubectl-netdrill

      - src: manpages/*.gz
        dst: /usr/share/man/man1/

homebrew_casks:
  - repository:
      owner: xenos76
      name: homebrew-tap
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill, a network troubleshooting plugin for Kubernetes.
    license: MIT
    skip_upload: false

    manpages:
      - manpages/kubectl-netdrill.1.gz
      - manpages/kubectl-netdrill-run.1.gz
      - manpages/kubectl-netdrill-pod.1.gz
      - manpages/kubectl-netdrill-debug.1.gz
      - manpages/kubectl-netdrill-deployment.1.gz

    completions:
      bash: "completions/{{ .ProjectName }}.bash"
      zsh: "completions/_{{ .ProjectName }}"
      fish: "completions/{{ .ProjectName }}.fish"

nix:
  - name: kubectl-netdrill
    repository:
      owner: xenos76
      name: nur-packages
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill
    path: pkgs/kubectl-netdrill/default.nix
    license: mit
    extra_install: |-
      installManPage manpages/kubectl-netdrill.1.gz
      installManPage manpages/kubectl-netdrill-run.1.gz
      installManPage manpages/kubectl-netdrill-pod.1.gz
      installManPage manpages/kubectl-netdrill-debug.1.gz
      installManPage manpages/kubectl-netdrill-deployment.1.gz
      installShellCompletion --cmd kubectl-netdrill \
        --bash <($out/bin/kubectl-netdrill completion bash) \
        --fish <($out/bin/kubectl-netdrill completion fish) \
        --zsh <($out/bin/kubectl-netdrill completion zsh)

krews:
  - name: netdrill
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/xenOs76/kubectl-netdrill"
    description: "kubectl-netdrill, a network troubleshooting plugin for Kubernetes."
    short_description: "kubectl-netdrill, a network troubleshooting plugin for Kubernetes."
    skip_upload: false
    repository:
      owner: xenos76
      name: krews
      branch: main

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
