---
version: 2
project_name: kubectl-netdrill
dist: ./dist/

force_token: github
env_files:
  gitea_token: ~/nope
  github_token: ~/nope

release:
  disable: false
  skip_upload: false
  github:
    owner: xenos76
    name: kubectl-netdrill

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/xenos76/kubectl-netdrill/cmd.Version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- .Arch }}
    wrap_in_directory: false
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

nfpms:
  - maintainer: Zeno Belli <xeno@os76.xyz>
    vendor: xenos76 on Github
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill, a network troubleshooting plugin for Kubernetes.
    license: MIT
    formats:
      - deb
      - rpm
    release: "1"

homebrew_casks:
  - repository:
      owner: xenos76
      name: homebrew-tap
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill, a network troubleshooting plugin for Kubernetes.
    license: MIT
    skip_upload: false

nix:
  - name: kubectl-netdrill
    repository:
      owner: xenos76
      name: nur-packages
    homepage: https://github.com/xenOs76/kubectl-netdrill
    description: kubectl-netdrill
    path: pkgs/kubectl-netdrill/default.nix
    license: mit
    # extra_install: |-
    #   # Add completions or manpages here if available in the future

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
