---
name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25"]

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> 2"
          args: release --clean
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_TOKEN }}

      - name: Refresh Go Report Card
        uses: creekorful/goreportcard-action@v1.0
